[toolchain]
anchor_version = "0.29.0" 
solana_version = "1.18.8" 

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_test = "CkrrcbKYHcBj8ozt79rVtKcrQ6iChsXWCraUPe6khynz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
